# Generated by Django 4.1.3 on 2022-11-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='destination',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='miles',
            new_name='watchers',
        ),
    ]
